spring.application.name=demo

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d71ak3p4tr6s73e92r00-a.oregon-postgres.render.com:5432/public_oehd
spring.datasource.username=test_pg
spring.datasource.password=wuottbTUQ2ooCgC4y5qUJuGL1CY1gNgn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
