spring.application.name=demo
# ===============================
# = DATA SOURCE
# ===============================
server.port=4040
spring.datasource.url=jdbc:postgresql://localhost:5432/pg_test
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional but Recommended
spring.jpa.open-in-view=false

# 32+ character secret used for request/response payload encryption
app.crypto.secret=qaz@wsx#edc$rfv%tgb^yhn&ujm*ik
app.crypto.enabled=false
app.crypto.excluded-paths=/report/**
