spring.application.name=demo
# ===============================
# = DATA SOURCE
# ===============================
#server.port=5432
#spring.datasource.url=jdbc:postgresql://test_pg:wuottbTUQ2ooCgC4y5qUJuGL1CY1gNgn@dpg-d71ak3p4tr6s73e92r00-a.oregon-postgres.render.com/public_oehd
#spring.datasource.username=test_pg
#spring.datasource.password=wuottbTUQ2ooCgC4y5qUJuGL1CY1gNgn
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d71ak3p4tr6s73e92r00-a.oregon-postgres.render.com:5432/public_oehd
spring.datasource.username=test_pg
spring.datasource.password=wuottbTUQ2ooCgC4y5qUJuGL1CY1gNgn
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

# Optional but Recommended
spring.jpa.open-in-view=false

# 32+ character secret used for request/response payload encryption
app.crypto.secret=qaz@wsx#edc$rfv%tgb^yhn&ujm*ik
app.crypto.enabled=false
app.crypto.excluded-paths=/report/**
